name: Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull latest code
        shell: powershell
        run: |
          docker exec devcontainer-frappe-1 bash -c "cd /workspace/development/frappe-bench/apps/lending && git fetch origin main && git reset --hard origin/main && cd /workspace/development/frappe-bench && bench restart"